[package]
name = "lab4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
thiserror = "1.0.49"
